# -*- coding: utf-8 -*-
"""final_overweight_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SvC9igStwwMNGEsR49HXqn2fs07m5iOv
"""

from keras import preprocessing
import keras
import pickle
import numpy as np
from matplotlib import pyplot as plt

def predict_list(img_list, model):
  pred_list = []
  images = np.zeros((len(img_list), 300, 150, 3), dtype='float32')
  i=0
  for path in img_list:
    img = preprocessing.image.load_img(path, target_size=(300, 150))
    images[i] = preprocessing.image.img_to_array(img)/255
    i+=1

  for i in range(len(img_list)):
    image = np.expand_dims(images[i], axis=0)
    pred = model.predict(image)
    if (pred[0][0] > pred[0][1]):
      pred_list.append(1)
    else:
      pred_list.append(0)

  return(pred_list)

if __name__ == "__main__":
    with open("overweight_detection_model.pickle", "rb") as file:
      model = pickle.load(file)

    liste = ["/content/1.jpg","/content/1347207.jpg", "/content/2.jpg", "/content/3.jpg", "/content/4.jpg", "/content/5.jpg", "/content/01.jpg", "/content/02.jpg", "/content/03.jpg" ]
    print(predict_list(liste, model))
